### ISSUE TITLE
RuntimeWarning when using Python interface

### ISSUE THREAD

**Issue by chrhansk** [felixlen/trlib#18]
I would like to solve the trust region problem in two dimensions for `H = -Id` and `g = 0` with a trust radius of 1 using the python3 (version 3.10.4) interface of `trlib` using the following code:

```python
import scipy.sparse
import numpy as np

import trlib

H = -1. * scipy.sparse.eye(2)

g = np.zeros((2,))

x, TR = trlib.trlib_solve(H, g, 1.0)
```

However, when I run the code I get the following messages:

```
<stdin>:1: RuntimeWarning: invalid value encountered in true_divide
<stdin>:1: RuntimeWarning: invalid value encountered in multiply
<stdin>:1: RuntimeWarning: trlib status -5
```

Is there a way to get `trlib` to solve the problem (I would expect to end up at some arbitrary point on the boundary)? I also tried with the C interface and got a message `TRLIB_TTR_HARD_INIT_LAM` back...

**Comment by felixlen** [comment]
The current implementation from the python interface investigates in the first $H$-invariant subspace spanned by $ g $, which is trivial in your case. The assume that the RuntimeWarnings occur due to normalization and need to check the code does not stop before doing that normalization of the `0` vector.

That aside the code in the current state of the python interface is not able to solve this problem, but could be extended towards this. The extension is nontrivial, one needs to check for exit in this condition and find a different starting vector not contained in the investigated invariant subspace (in that example any nonzero vector does the job, in general a random vector will do except on a set of measure 0) and continue the Lanczos process.

**Comment by chrhansk** [comment]
I am asking because I am curious about points satisfying the necessary but not the sufficient stationarity criteria, for example the point `(0,0)` for the objective `-1/2(x^2+y^2)`. It would be interesting to at least produce a warning messages in these cases.

In the C API, I would have to set an appropriate `ctl_invariant` and implement the `TRLIB_CLA_NEW_KRYLOV` step, correct?

The Python extension should probably just produce a more meaningful error message in this case, right?
